# Generated by Django 3.0.8 on 2020-09-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200905_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(related_name='following', to='network.Follower'),
        ),
    ]
