# Generated by Django 3.0.8 on 2020-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200905_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_post', to='network.Like'),
        ),
    ]
